---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "editor"
  annotations:
    fluxcd.io/automated: "true"
  namespace: "ipp"
  labels:
    app: editor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: editor
  template:
    metadata:
      labels:
        app: editor
    spec:
      containers:
      - image: 425563513848.dkr.ecr.ap-southeast-1.amazonaws.com/editor:7ffd7f15ded9ff8b54f61951cd273e5503a10a5b
        imagePullPolicy: Always
        name: editor
        ports:
        - containerPort: 4001
