apiVersion: apps/v1
kind: Deployment
metadata:
  name: "user-deployment"
    annotations:
      fluxcd.io/automated: "true"
  namespace: "instaclone"
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - image: 650965765717.dkr.ecr.ap-southeast-1.amazonaws.com/test:d940c96a1efdbd710aa183a74e6f91f7af7b12f6
          imagePullPolicy: Always
          name: user
          ports:
            - containerPort: 5000
