apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: instaclone
spec:
  selector:
    app: user
  type: NodePort
  ports:
   -  protocol: TCP
      port: 5000
      targetPort: 5000