---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "chat"
  annotations:
    fluxcd.io/automated: "true"
  namespace: "ipp"
  labels:
    app: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - image: 425563513848.dkr.ecr.ap-southeast-1.amazonaws.com/chat:2e00e977f075f42a92be306798a1d9e6d0256257
        imagePullPolicy: Always
        name: chat
        ports:
        - containerPort: 5002
