---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "match"
  annotations:
    fluxcd.io/automated: "true"
  namespace: "ipp"
  labels:
    app: match
spec:
  replicas: 3
  selector:
    matchLabels:
      app: match
  template:
    metadata:
      labels:
        app: match
    spec:
      containers:
      - image: 425563513848.dkr.ecr.ap-southeast-1.amazonaws.com/match:b8fafeb0cb60db7956b571d8e9e2b9b965e7e1dc
        imagePullPolicy: Always
        name: match
        ports:
        - containerPort: 5000
