---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "user"
  annotations:
    fluxcd.io/automated: "true"
  namespace: "ipp"
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - image: 425563513848.dkr.ecr.ap-southeast-1.amazonaws.com/user:7ffd7f15ded9ff8b54f61951cd273e5503a10a5b
        imagePullPolicy: Always
        name: user
        ports:
        - containerPort: 5001
