
name: Build and Push POST MS to EKS
on:
  push:
    # branches:
    # - 'Backend/**'
  # pull_request:
  #   types: [closed]
      
env:
  AWS_DEFAULT_REGION: ap-southeast-1
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CONTAINER_IMAGE: match:${{ github.sha }}

jobs:
  build-and-push:
    name: Build and deploy MATCH MS to ECR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    # Add steps here like linting, testing, minification, etc.

    - name: Setup ECR
      run: |
        # Login to AWS ECR
        $( aws ecr get-login --no-include-email )
    - name: Build and tag the image
      working-directory: ./backend/match
      run: |
        # Build and tag the image
        docker build .
          
    - name: Push the image into ECR
#      if: github.ref == 'refs/heads/master'
      run: |
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE
    # Add additional steps here like scanning of image
